import sys

def main(argv):
    argc = len(sys.argv)
    if argv[1] == "maketable":
        of = open("out.txt",'w')
        of.write("; Generated by gbfreq.py\nFreqTable:")
        for    i in range(0,256):
            if i % 12 == 0:
                of.write("\n    dw      ")
            x = float(argv[0]) * pow(2, (i - 69) / 12)
            y = (2048 * (x - 64)) / x
            of.write('$%x,' % int(round(y)))
        of.close()
    else:
        x = float(argv[0]) * pow(2, (float(argv[1]) - 69) / 12)
        y = (2048 * (x - 64)) / x
        print("a =",argv[0],"  midi note:",argv[1],"  freq:",x,"  GB:",'0x%x'%int(round(y)))
    
if __name__ == "__main__":
    main(sys.argv[1:])